//	============================================================================
//	Definitions.H													80 columns
//	Reece Hart	(reece@dasher.wustl.edu)							tab=4 spaces
//	Washington University School of Medicine, St. Louis, Missouri
//	This source is hereby released to the public domain.  Bug reports, code
//	contributions, and suggestions are appreciated (to email address above).
//	-    -    -    -    -    -    -    -    -    -    -    -    -    -    -    -
//	Simple definitions for the automated sequencing analysis project.
//	========================================|===================================

typedef long	trace_t;					// sampled data type
typedef	long	tracepos;					// index in the trace_t array

